database:
  host: database:3306
  schema: pogs
  url: jdbc:mysql://${database.host}/${database.schema}?useSSL=false
  username: root
  password: ${POGS_PASSWORD}
plugin:
  dir: /app/plugins
images:
  dir: /app/uploadedFiles
spring:
  redis:
    host: redisserver
    port: 6379