language: java
jdk: openjdk8
sudo: false

cache:
  yarn: true
  directories:
    - $HOME/.m2

before_install:
  - gem install dpl --source http://rubygems.org
  - source others/travis/travis_rc.sh
  - others/travis/before_script.sh

addons:
  mariadb: '10.2'
service:
  - redis-server
install: true

script:
  - others/travis/build.sh

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file: "target/*"
  skip_cleanup: true
  name: "pogs-0.0.1-SNAPSHOT.jar"
  on:
    branch: master
