language: java
jdk: openjdk8
sudo: false

cache:
  yarn: true
  directories:
    - $HOME/.m2

env:
  - RUN_SLOW_TESTS=false

before_install:
  - gem install dpl --source http://rubygems.org
  - source others/travis/travis_rc.sh
  - others/travis/before_script.sh

service:
  - redis-server
  - mysql

install: true

script:
  - others/travis/build.sh

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file: "target/pogs-0.0.1-SNAPSHOT.jar"
  skip_cleanup: true
  name: "pogs-0.0.1-SNAPSHOT.jar"
  on:
    branch: master
