server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always
  servlet:
    session:
      timeout: 7d
  compression:
    enabled: true
plugin:
  dir: ${user.home}/plugins


spring:
  profiles:
    include: database-config
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    hikari:
      minimumIdle: 2
      maximumPoolSize: 50
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000
  servlet:
    multipart:
      max-file-size: -1
  security:
    filter:
      dispatcher-types: ASYNC,REQUEST,ERROR
  mvc:
    favicon:
      enabled: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths:
            - "/js/**"      # /static/js - our JavaScript files
            - "/css/**"     # /(static|dist)/css - our CSS files
            - "/vendor/**"  # /dist/vendor - external dependencies (from yarn)
      cache: false
    cache:
      period: 1d
    # use comma-separated list to override default value
    static-locations: >
      classpath:/dist/,
      classpath:/static/

logging:
  level:
    ROOT: WARN
    org.springframework: INFO
    org.springframework.jmx: WARN
    org.springframework.boot.actuate: WARN
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: WARN
    org.springframework.boot.web.servlet.FilterRegistrationBean: DEBUG
    org.springframework.web.servlet.handler.SimpleUrlHandlerMapping: WARN
    edu.mit.cci: DEBUG

---

spring:
  profiles: development
  resources:
    # use comma-separated list to override default value
    static-locations: >
      file:src/main/resources/static/,
      file:src/main/resources/dist/,
      file:src/main/resources/plugins/,
      classpath:/dist/,
      classpath:/static/,
      classpath:/plugins/
